Karpefors/Tendril

R/colorfuncs.R
Ports minimal routines to manipulate colors. These routines are dependencies of the routines that will come later.
=> Added color functions

DESCRIPTION, Makefile, README.md
Added makefile to create the packrat environment.
Added instructions to the README to clarify how to deploy.
Needs same information for windows and linux.
=> Added makefile to create environment and instructions

R/colorfuncs.R, R/plot.term.R
Adds the plot.term function to the package.
=> Add plot.term function

R/colorfuncs.R, R/plot.permut.perc.simple.R
Adds the plot.permut.perc.simple routine to the package
=> Added plot.permut.perc.simple

R/ae.time.series.R, R/colorfuncs.R
Adds the ae.time.series function to the package.
=> Add ae.time.series function

DESCRIPTION, R/plot.interactive.R
Adds the plot.interactive routine to the package
=> Add plot.interactive routine

DESCRIPTION, README.md
=> Re-released as 0.7

.gitattributes
Usual problem of CRLF with windows/non-windows development.
At least it saves ASCII...
=> Added git attributes to handle multiplatform development

.Rbuildignore
Ignore some files from the build of R to ensure they are not reported at check
=> Ignoring files for R build

.gitignore
Ignores some files that are boilerplate for R running
=> Added ignored files

.Rbuildignore, .gitignore, R/colorfuncs.R, R/plot.interactive.R, R/plot.permut.perc.simple.R, R/plot.term.R, R/plotbasic.R
Extracted the palette creation as a function.
en-passant fix of a typo for the layout function scope (was graphics, should have been plotly)
=> Refactored palette to a separate function

R/plot.interactive.R, R/plotbasic.R, R/plotpercentile.R, R/plotpermutation.R
Added visualisation of left and right labels. Turns out that they were already there, just white on white.
=> Showing labels in the plots

R/plotpercentile.R, R/plotpermutation.R
Updated colouring of permutation and percentile plots to show actual arm with p-adj colouring
=> Change colouring perm perc

R/ggplot2_plotbasic.R, R/plot.Tendril.R, R/plotly_plotbasic.R
Amended basic plot to accept term argument.  NULL (default) = all tendrils; single value = single tendril; vector = listed tendrils
=> Allow single, multiple or all tendrils to be plotted

R/plot_timeseries.R
As discussed in call 14-Oct - consolidated changes to the time series plot - plot_timeseries
=> Consolidated changes to the time series plots

R/plot.Tendril.R, R/plot.TendrilPerm.R, man/plot.TendrilPerm.Rd, man/plot.tendril.Rd, man/plot_timeseries.Rd
=> Fixed signature of plot methods and documentation

R/plotly_plotbasic.R
Added TermsCount wit the label 'Frequency:' to the hover text in the interactive plot.  Implemented for all colourings and number of terms.
=> Add Frequency to hover text

CHANGELOG.md, DESCRIPTION, README.md, man/plot_timeseries.Rd
=> Release branch for v0.8.0

R/Tendril.R, R/Tendril.stat.R, R/formatting.R
=> Tendril keep other input variables

R/Tendril.R, R/validation.R, tests/testthat/test_tendrilData.R
=> Removed dot from validate_tendril_results

tests/testthat/test_tendrilData.R
=> Fixed some tests involving validate_tendril_data

R/Tendril.stat.R, R/validation.R
=> Moved and renamed validate_tendril_stat

R/TendrilPerm.R, R/validation.R
=> Moved tendril.perm and tendril.day validation

R/plot.Tendril.R, tests/testthat/test_tendrilData.R
=> Added error message for plotting with an unexisting term

R/plot_timeseries.R
=> Fixed incorrect indexing for plot timeseries

R/plotly_plotbasic.R
=> Same palette for plotly plots

R/plotly_plotbasic.R
=> Removed opacity term

R/plot.Tendril.R
The terms list is actually in tendrilobj$data$Terms, not on tendrilobj$Terms
=> Fix for incorrect solution of #74

R/ggplot2_plotbasic.R
=> Fixed label p-value to log(p-val)

R/plotly_plotbasic.R
=> Fixed incorrect scale for limited tendril plotting.

R/ggplot2_plotbasic.R, R/plotly_plotbasic.R
Fixes #93 
Note that this PR is built on top of #95 (to prevent conflicts)
=> Add FDR.tot for coloring

R/aaa.R, R/ggplot2_plotbasic.R, R/plot_percentile.R, R/plot_permutation.R, R/plotly_plotbasic.R
=> Added global variable for coloring options

CHANGELOG.md, DESCRIPTION, README.md
Changes:
- #98 Fixed missing FDR.tot in other coloring scale selections.
=> Release v2.0.2
